In [6]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

# df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int


""" converting categorical data into numerical using get_dummies """
df = pd.DataFrame(data)
df = pd.get_dummies(df, drop_first=True, dtype=int)
print(df)



   Feature2  Feature1_20  Feature1_Thirty
0       5.5            0                0
1       6.7            1                0
2       8.9            0                1


In [66]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
""" calculates Mean """
mean_value = df.mean() 
"""
fillna - default creates new dataframe
inplace=True - displays with modification made in dataframe"""
df.fillna(mean_value, inplace=True)  # Error: fillna() does not modify in place

print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [60]:
#3.from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([1, 2, 3, 4, 5])  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])


""" to make the X as 2D - i used pandas dataframe"""
x_df= pd.DataFrame(X)
y_df= pd.DataFrame(y)
model = LinearRegression()
model.fit(x_df, y_df)

model.predict([[5]])


array([[10.]])

In [21]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D

scaler = StandardScaler()
""" passing data as 2D - using pandas dataframe """
scaled_data = scaler.fit_transform(pd.DataFrame(data))  

print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [43]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

""" converting categorical into numerical"""
y_df = pd.get_dummies(y,drop_first=True,dtype=int)

model = LogisticRegression()
model.fit(X, y_df)

model.predict([[3,4]])


C:\anaconda3\envs\aids\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1])

In [67]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
""" 2D array = [[ ]] """
encoded = encoder.fit_transform(df[['Category']])  # Error: Data should be reshaped
print(encoded)


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 3)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0


In [8]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
""" solved inconsistent No of samples by adding 1 data in y """
y = [0, 1, 0, 1]   

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train, X_test, y_train, y_test)

[[7, 8], [3, 4], [1, 2]] [[5, 6]] [1, 1, 0] [0]


In [14]:
#7.from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.linear_model import LogisticRegression
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels
""" converting categorical into numerical """
y_train = pd.get_dummies(y_train, drop_first=True, dtype=int)

model = LogisticRegression()
model.fit(X_train, y_train)

model.predict([[3,4]])

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1])

In [22]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

""" Replace nan with mean of the column using simple imputer """
from sklearn.impute import SimpleImputer
impute = SimpleImputer(strategy='mean')
x_train = impute.fit_transform(X_train)

model = LinearRegression()
model.fit(x_train, y_train)  

model.predict([[1,2]])

array([10.])

In [26]:
#9.
from sklearn.tree import DecisionTreeClassifier

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed

""" convert categorical into numerical """
y_train = pd.get_dummies(y_train, drop_first=True, dtype=int)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)


model.predict([[3,4]])

array([0])

In [41]:
#10.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

""" to handle the unreliable output - do the standardization in order to normalize the large scale difference """
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
# print(X_train)

model = SVC()
model.fit(X_train, y_train)
standardize_input = sc.transform([[3, 300]])
print(model.predict(standardize_input))  # Unreliable output due to large-scale difference


[0]
